# Generated by Django 4.2.7 on 2024-01-04 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_alter_addressee_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='id_addressee',
            new_name='addressee',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='id_sender',
            new_name='sender',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='id_transport',
            new_name='transport',
        ),
        migrations.AddField(
            model_name='transport',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
