# Generated by Django 4.2.7 on 2024-01-07 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_sender_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='arrived',
        ),
        migrations.RemoveField(
            model_name='package',
            name='delivered',
        ),
        migrations.RemoveField(
            model_name='package',
            name='departed',
        ),
        migrations.RemoveField(
            model_name='package',
            name='packaged',
        ),
        migrations.RemoveField(
            model_name='package',
            name='received',
        ),
    ]
