# Generated by Django 4.2.7 on 2024-01-07 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_arrived_delivered_departure_packaged_received_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arrived',
            old_name='package_id',
            new_name='package',
        ),
        migrations.RenameField(
            model_name='delivered',
            old_name='package_id',
            new_name='package',
        ),
        migrations.RenameField(
            model_name='departure',
            old_name='package_id',
            new_name='package',
        ),
        migrations.RenameField(
            model_name='packaged',
            old_name='package_id',
            new_name='package',
        ),
        migrations.RenameField(
            model_name='received',
            old_name='package_id',
            new_name='package',
        ),
    ]
