# Generated by Django 4.2.7 on 2024-01-07 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_package_id_arrived_package_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='arrived',
        ),
        migrations.RemoveField(
            model_name='package',
            name='delivered',
        ),
        migrations.RemoveField(
            model_name='package',
            name='departure',
        ),
        migrations.RemoveField(
            model_name='package',
            name='packaged',
        ),
        migrations.RemoveField(
            model_name='package',
            name='received',
        ),
        migrations.AlterField(
            model_name='arrived',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.package'),
        ),
        migrations.AlterField(
            model_name='delivered',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.package'),
        ),
        migrations.AlterField(
            model_name='departure',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.package'),
        ),
        migrations.AlterField(
            model_name='packaged',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.package'),
        ),
        migrations.AlterField(
            model_name='received',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.package'),
        ),
    ]
